#include "Bake.h"

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <format>
#include <optional>
#include <string_view>

namespace
{
// The notdef box every face carries at index 0, synthesised rather than taken from the font: a face
// that lacked the replacement character would have nothing to answer a missing code point with, and
// one that had it would answer differently from its neighbour on the ladder. A hollow rectangle inset
// by one texel, which at 5x8 is still a mark and at 32x64 is still obviously not a letter.
std::vector<std::uint8_t> Notdef(const BdfFont& font)
{
	const std::int32_t rowBytes = font.RowBytes();
	std::vector<std::uint8_t> rows(static_cast<std::size_t>(rowBytes) * static_cast<std::size_t>(font.CellHeight));

	for (std::int32_t y = 1; y + 1 < font.CellHeight; ++y)
	{
		for (std::int32_t x = 1; x + 1 < font.CellWidth; ++x)
		{
			const bool edge = x == 1 || x + 2 == font.CellWidth || y == 1 || y + 2 == font.CellHeight;

			if (!edge)
			{
				continue;
			}

			const std::size_t index =
				static_cast<std::size_t>(y) * static_cast<std::size_t>(rowBytes) + static_cast<std::size_t>(x / 8);

			rows[index] = static_cast<std::uint8_t>(rows[index] | (0x80U >> (x % 8)));
		}
	}

	return rows;
}

std::string Identifier(std::string_view name)
{
	std::string identifier;

	for (const char character : name)
	{
		identifier.push_back(
			(character >= 'a' && character <= 'z') || (character >= 'A' && character <= 'Z') ||
					(character >= '0' && character <= '9') ?
				character :
				'_'
		);
	}

	return identifier;
}

void AppendBytes(std::string& text, std::span<const std::uint8_t> bytes)
{
	constexpr std::size_t PerLine = 16;

	for (std::size_t index = 0; index < bytes.size(); ++index)
	{
		text += index % PerLine == 0 ? "\n\t" : " ";
		text += std::format("{:#04x},", bytes[index]);
	}

	text += "\n";
}
} // namespace

Result<std::string> Bake(std::vector<FaceSource> faces, std::string* diagnostic)
{
	const auto fail = [diagnostic](std::string_view what) {
		if (diagnostic != nullptr)
		{
			*diagnostic = what;
		}

		return Failure(EINVAL, "baking a font table");
	};

	if (faces.empty())
	{
		return fail("no fonts to bake, so nothing would ever answer Faces()");
	}

	std::ranges::sort(faces, {}, [](const FaceSource& face) { return face.Font.CellHeight; });

	std::string text = "// Generated by Tools/Fonts from the BDF files in Vendor/Spleen. Do not edit.\n"
					   "//\n"
					   "// The font is Spleen, by Frederic Cambus, under the BSD 2-Clause licence carried in\n"
					   "// Vendor/Spleen/LICENSE. What is baked is Tools/Fonts/Bake.h's declared coverage,\n"
					   "// intersected with what each size actually has.\n"
					   "\n"
					   "#include \"Text/Font.h\"\n"
					   "\n"
					   "namespace\n"
					   "{\n";

	std::string ladder;

	for (const FaceSource& face : faces)
	{
		const std::string identifier = Identifier(face.Name);
		const std::size_t stride =
			static_cast<std::size_t>(face.Font.RowBytes()) * static_cast<std::size_t>(face.Font.CellHeight);

		std::vector<std::uint8_t> bitmaps = Notdef(face.Font);

		if (bitmaps.size() != stride)
		{
			return fail("a notdef box that is not one cell, which is a bake bug rather than a font one");
		}

		std::string runs;
		std::size_t count = 0;

		for (const CodeRange& range : RequestedCoverage)
		{
			std::optional<char32_t> first;
			std::uint32_t firstIndex = 0;

			const auto close = [&runs, &first, &firstIndex](char32_t last) {
				if (first.has_value())
				{
					runs += std::format(
						"\t{{ {:#x}, {:#x}, {} }},\n",
						static_cast<std::uint32_t>(*first),
						static_cast<std::uint32_t>(last),
						firstIndex
					);
					first.reset();
				}
			};

			for (char32_t code = range.First; code <= range.Last; ++code)
			{
				const auto glyph = std::ranges::lower_bound(face.Font.Glyphs, code, {}, &BdfGlyph::Code);
				const bool present = glyph != face.Font.Glyphs.end() && glyph->Code == code;

				if (!present)
				{
					close(code - 1);

					continue;
				}

				if (glyph->Rows.size() != stride)
				{
					return fail("a glyph whose bitmap is not one cell, which the parser should have caught");
				}

				if (!first.has_value())
				{
					first = code;
					firstIndex = static_cast<std::uint32_t>(bitmaps.size() / stride);
				}

				bitmaps.insert(bitmaps.end(), glyph->Rows.begin(), glyph->Rows.end());
				++count;
			}

			close(range.Last);
		}

		if (count == 0)
		{
			return fail("a font with none of the requested coverage, which is the wrong file or the wrong ranges");
		}

		text += std::format("constexpr std::uint8_t {}Bitmaps[] = {{", identifier);
		AppendBytes(text, bitmaps);
		text += "};\n\n";

		text += std::format("constexpr CodeRun {}Runs[] = {{\n{}}};\n\n", identifier, runs);

		ladder += std::format(
			"\tFace{{ \"{}\", {}, {}, {}, {}Runs, {}Bitmaps }},\n",
			face.Name,
			face.Font.CellWidth,
			face.Font.CellHeight,
			face.Font.Ascent,
			identifier,
			identifier
		);
	}

	text += std::format("const Face Ladder[] = {{\n{}}};\n}} // namespace\n\n", ladder);
	text += "std::span<const Face> Faces() noexcept\n{\n\treturn Ladder;\n}\n";

	return text;
}
