# The Wayland client bindings, generated at build time into the build tree.
#
# Decision 2 settles three things about this and they are all visible in the rules below: the bindings
# are gyro's rather than libwayland's, they are generated by a host tool with a hand-rolled parser and
# no scripting-language dependency, and **no generated code is ever written into the source tree.**
# The last one is the reason the outputs live under `${CMAKE_BINARY_DIR}/Generated` and are reached by
# an include path rather than by a relative include: a header in Source/ that was produced by a build
# is a header somebody eventually edits, and the edit survives until the next clean build.
#
# **The generator is built as a separate project, by ExternalProject, and that is not ceremony.**
# Tools/Bindings/CMakeLists.txt argues it: the generator runs on the machine doing the building and
# gyro runs on the machine being built for, and one build tree holds one toolchain. Reached by
# `add_subdirectory` it would be compiled with gyro's toolchain, which on the day gyro is
# cross-compiled for an ARM panel means a build tool that cannot be executed. Two toolchains means two
# projects, and ExternalProject is how CMake spells that.
#
# **The protocol XML is located, never hardcoded.** wayland-scanner and wayland-protocols each publish
# a `pkgdatadir`, and a distribution is entitled to put them anywhere; `/usr/share` is a guess that is
# right until it is not, on the machine of whoever is least equipped to work out why.

include(ExternalProject)

find_package(PkgConfig REQUIRED)
pkg_get_variable(GYRO_WAYLAND_DATA_DIR wayland-scanner pkgdatadir)
pkg_get_variable(GYRO_WAYLAND_PROTOCOLS_DIR wayland-protocols pkgdatadir)

# Named with the package to install, the way the liburing block in CMakeLists.txt is, and for the same
# reason: the machine that hits this is a machine somebody is setting up and the fix is one command.
if(NOT GYRO_WAYLAND_DATA_DIR OR NOT GYRO_WAYLAND_PROTOCOLS_DIR)
	message(FATAL_ERROR
		"wayland.xml and the protocol suite are what gyro's client bindings are generated from, and "
		"pkg-config could not locate them. Install wayland-devel and wayland-protocols-devel (Fedora) "
		"or libwayland-dev and wayland-protocols (Debian)."
	)
endif()

# The generator, built for the host. BUILD_ALWAYS is what keeps an edit to the emitter from producing
# a stale binding: ExternalProject tracks no source files of its own, so without it the sub-build runs
# once and never again. It costs a no-op ninja invocation per build, and the generation rule below
# depends on the *executable* rather than on the stamp — so a sub-build that relinked nothing leaves
# the binary's timestamp alone and nothing downstream re-runs.
#
# **Between the two of them nothing generated can go stale**, and it is worth saying which covers
# what. An edit to the protocol XML is caught by the generation rule's own DEPENDS below. An edit to
# the *emitter* is caught here: BUILD_ALWAYS recompiles it, the relink moves the executable's
# timestamp, and the rule below depends on the executable. A protocol dropped from the list is caught
# by the generator itself, which deletes anything in its output directory it did not just write.
#
# **Rejected: a CONFIGURE_DEPENDS glob of the generator's sources, named as a dependency as well.** It
# reads like belt and braces and costs a full rebuild of the tree on every single build — the glob
# verification runs each time, re-runs CMake, and a regenerated build.ninja drops the stored header
# dependencies for every translation unit. The mechanism above already covers what the glob was for,
# so the redundancy bought nothing and charged several minutes for it.
set(GYRO_BINDINGS_BINARY_DIR ${CMAKE_BINARY_DIR}/Tools/Bindings)
set(GYRO_BINDINGS_TOOL ${GYRO_BINDINGS_BINARY_DIR}/GyroBindings)


ExternalProject_Add(BindingsGenerator
	SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/Tools/Bindings
	BINARY_DIR ${GYRO_BINDINGS_BINARY_DIR}
	CMAKE_ARGS
		-DCMAKE_BUILD_TYPE=Release
	BUILD_ALWAYS ON
	BUILD_BYPRODUCTS ${GYRO_BINDINGS_TOOL}
	INSTALL_COMMAND ""
	# It builds its own tests, and the main tree runs them — a generator whose parser is not exercised
	# by `ctest --test-dir build` is one whose failures arrive as compiler errors in generated code.
	TEST_COMMAND ""
	USES_TERMINAL_BUILD OFF
)

add_test(
	NAME Bindings
	COMMAND ${GYRO_BINDINGS_BINARY_DIR}/BindingsParserTests
)

# `wl_surface` to `WlSurface`, `xdg-shell` to `XdgShell` — Tools/Bindings/Naming.h's rule, restated
# here because the build has to know an output file's name before the generator has run once.
function(gyro_pascal OUTPUT WIRE)
	string(REPLACE "-" ";" PARTS "${WIRE}")
	string(REPLACE "_" ";" PARTS "${PARTS}")

	set(RESULT "")

	foreach(PART IN LISTS PARTS)
		if(PART STREQUAL "")
			continue()
		endif()

		string(SUBSTRING "${PART}" 0 1 HEAD)
		string(SUBSTRING "${PART}" 1 -1 TAIL)
		string(TOUPPER "${HEAD}" HEAD)
		string(APPEND RESULT "${HEAD}${TAIL}")
	endforeach()

	set(${OUTPUT} "${RESULT}" PARENT_SCOPE)
endfunction()

# One library of generated bindings.
#
#   gyro_add_bindings(WaylandProtocols PROTOCOLS wayland stable/xdg-shell/xdg-shell ...)
#
# Each protocol is named by its path *within* one of the two pkgdatadirs and without the `.xml`, which
# is the layout upstream publishes and the spelling somebody adding a protocol can copy off the
# wayland-protocols tree. Both roots are searched, because `wayland.xml` lives in one and everything
# else in the other.
#
# **Every protocol is one invocation of the generator.** Tools/Bindings/Emit.h needs the whole set to
# resolve a reference that leaves its own document — `zwp_linux_buffer_params_v1.created` hands back a
# `wl_buffer` — and a per-file rule would either guess or emit an untyped id where the protocol was
# specific. One rule also means adding a protocol regenerates all of them, rather than leaving the
# file that would have to include it stale until somebody clears the build directory.
function(gyro_add_bindings TARGET)
	cmake_parse_arguments(PARSE_ARGV 1 BINDINGS "" "" "PROTOCOLS")

	if(BINDINGS_UNPARSED_ARGUMENTS)
		message(FATAL_ERROR "gyro_add_bindings(${TARGET}): unexpected argument ${BINDINGS_UNPARSED_ARGUMENTS}")
	endif()
	if(NOT BINDINGS_PROTOCOLS)
		message(FATAL_ERROR "gyro_add_bindings(${TARGET}): no PROTOCOLS")
	endif()

	set(GENERATED ${CMAKE_BINARY_DIR}/Generated)
	set(INPUTS "")
	set(OUTPUTS "")
	set(SOURCES "")

	foreach(PROTOCOL IN LISTS BINDINGS_PROTOCOLS)
		set(FOUND "")

		foreach(ROOT ${GYRO_WAYLAND_DATA_DIR} ${GYRO_WAYLAND_PROTOCOLS_DIR})
			if(EXISTS "${ROOT}/${PROTOCOL}.xml")
				set(FOUND "${ROOT}/${PROTOCOL}.xml")
				break()
			endif()
		endforeach()

		# A protocol the machine does not have is a missing package rather than a typo, most of the
		# time — staging protocols arrive in wayland-protocols releases and a distribution may be a
		# version behind. Both roots are named so the reader can see where it looked.
		if(NOT FOUND)
			message(FATAL_ERROR
				"gyro_add_bindings(${TARGET}): ${PROTOCOL}.xml is in neither "
				"${GYRO_WAYLAND_DATA_DIR} nor ${GYRO_WAYLAND_PROTOCOLS_DIR}. It arrives with "
				"wayland-protocols; a distribution one release behind may not carry it yet."
			)
		endif()

		get_filename_component(STEM "${PROTOCOL}" NAME_WE)
		gyro_pascal(UNIT "${STEM}")

		list(APPEND INPUTS "${FOUND}")
		list(APPEND OUTPUTS "${GENERATED}/Wayland/${UNIT}.h" "${GENERATED}/Wayland/${UNIT}.cpp")
		list(APPEND SOURCES "${GENERATED}/Wayland/${UNIT}.cpp")
	endforeach()

	# **The rule's output is a stamp and the generated files are byproducts**, which is what makes
	# "never stale" and "never rebuild the world" hold at once. The generator does not rewrite a file
	# whose text is unchanged — that is the whole reason a protocol-suite bump does not recompile
	# everything downstream — and a rule whose declared outputs keep their old timestamps is a rule
	# ninja considers dirty on every build, forever. The stamp is touched unconditionally, so the rule
	# settles; the generated files carry their real timestamps, so each translation unit recompiles
	# only if its own text moved.
	set(STAMP ${CMAKE_CURRENT_BINARY_DIR}/${TARGET}.stamp)

	add_custom_command(
		OUTPUT ${STAMP}
		COMMAND ${GYRO_BINDINGS_TOOL} --output ${GENERATED} ${INPUTS}
		COMMAND ${CMAKE_COMMAND} -E touch ${STAMP}
		BYPRODUCTS ${OUTPUTS}
		# Everything a generated file's text can depend on, so none of them can go stale: the protocol
		# XML it is derived from, and the generator that derived it. The executable rather than the
		# ExternalProject stamp, per the note above — the stamp moves every build and the executable
		# moves only when the generator was actually relinked, which is what an emitter edit does and a
		# no-op build does not. The target is named as well, which is what orders this rule after the
		# sub-build rather than racing it.
		DEPENDS
			${INPUTS}
			${GYRO_BINDINGS_TOOL}
			BindingsGenerator
		COMMENT "Generating Wayland client bindings"
		VERBATIM
	)

	add_custom_target(${TARGET}Generate DEPENDS ${STAMP})

	# A plain library rather than a gyro_add_module, and the difference is where the sources are.
	# CheckPortability and CheckLayering walk Source/ — they police what may run on the frame thread
	# and what a module may name, and neither question is asked of a file the build wrote. What holds
	# this target in place instead is its one edge: it links Wire and nothing else, so a generated
	# binding that reached for a platform header would not link.
	# Written by a rule whose declared output is the stamp, so CMake has to be told they will exist.
	set_source_files_properties(${SOURCES} PROPERTIES GENERATED TRUE)

	add_library(${TARGET} STATIC ${SOURCES})
	add_dependencies(${TARGET} ${TARGET}Generate)
	target_link_libraries(${TARGET} PUBLIC Wire)
	target_include_directories(${TARGET} PUBLIC ${GENERATED})
endfunction()
