# The Wayland bindings, generated at build time into the build tree — both directions.
#
# **There are two arms and they point opposite ways over the same XML.** The client arm emits proxies
# and listeners over gyro's own codec, and is what the nested backend speaks to its host. The server
# arm emits resources and handlers over `libwayland-server`, and is what gyro speaks to its clients.
# They are separate targets with separate protocol lists, because what gyro needs from a host and what
# gyro offers a client are different sets that happen to be described by the same files.
#
# Decision 2 settles three things about this and they are all visible in the rules below: the bindings
# are gyro's rather than libwayland's, they are generated by a host tool with a hand-rolled parser and
# no scripting-language dependency, and **no generated code is ever written into the source tree.**
# The last one is the reason the outputs live under `${CMAKE_BINARY_DIR}/Generated` and are reached by
# an include path rather than by a relative include: a header in Source/ that was produced by a build
# is a header somebody eventually edits, and the edit survives until the next clean build.
#
# **The generator is built as a separate project, by ExternalProject, and that is not ceremony.**
# Tools/Bindings/CMakeLists.txt argues it: the generator runs on the machine doing the building and
# gyro runs on the machine being built for, and one build tree holds one toolchain. Reached by
# `add_subdirectory` it would be compiled with gyro's toolchain, which on the day gyro is
# cross-compiled for an ARM panel means a build tool that cannot be executed. Two toolchains means two
# projects, and ExternalProject is how CMake spells that.
#
# **The protocol XML is located, never hardcoded.** wayland-scanner and wayland-protocols each publish
# a `pkgdatadir`, and a distribution is entitled to put them anywhere; `/usr/share` is a guess that is
# right until it is not, on the machine of whoever is least equipped to work out why.
#
# **There is a third root and it is the repository's own**, `Protocols/`, searched first. gyro serves
# one protocol nobody else has written — the chords a shell claims — and a first-party document is not
# subject to what a distribution happened to ship: searching it ahead of the two package directories
# is what makes a `gyro_` name resolve to the file in this tree whatever is installed on the machine.
# It is a directory rather than a file list because the second one will not be the last, and it sits
# beside `Source/` rather than inside it because nothing in `Source/` is compiled from XML.
#
# **`libwayland-server` is found here rather than in Tools/Bindings.** The generator never links it —
# it emits text — so the dependency belongs where the emitted text is compiled, which is this file and
# the server target it declares.

include(ExternalProject)

find_package(PkgConfig REQUIRED)
pkg_get_variable(GYRO_WAYLAND_DATA_DIR wayland-scanner pkgdatadir)
pkg_get_variable(GYRO_WAYLAND_PROTOCOLS_DIR wayland-protocols pkgdatadir)

# gyro's own, in this repository. Named absolutely because `gyro_add_bindings` is called from the top
# level and a relative path would be read against whichever directory reached it.
set(GYRO_FIRST_PARTY_PROTOCOLS_DIR ${CMAKE_CURRENT_SOURCE_DIR}/Protocols)

# Named with the package to install, the way the liburing block in CMakeLists.txt is, and for the same
# reason: the machine that hits this is a machine somebody is setting up and the fix is one command.
if(NOT GYRO_WAYLAND_DATA_DIR OR NOT GYRO_WAYLAND_PROTOCOLS_DIR)
	message(FATAL_ERROR
		"wayland.xml and the protocol suite are what gyro's client bindings are generated from, and "
		"pkg-config could not locate them. Install wayland-devel and wayland-protocols-devel (Fedora) "
		"or libwayland-dev and wayland-protocols (Debian)."
	)
endif()

# Decision 2's other half: the server codec is libwayland's, behind gyro's seam. The generated server
# bindings are the wrapper that decision asks for in exchange — a typed constructor that cannot make a
# resource without an implementation, and a dispatch table generated from the XML so it cannot have a
# hole. Those two close the only `wl_abort` sites a client can reach.
pkg_check_modules(WAYLAND_SERVER REQUIRED IMPORTED_TARGET wayland-server)

# The generator, built for the host. BUILD_ALWAYS is what keeps an edit to the emitter from producing
# a stale binding: ExternalProject tracks no source files of its own, so without it the sub-build runs
# once and never again. It costs a no-op ninja invocation per build, and the generation rule below
# depends on the *executable* rather than on the stamp — so a sub-build that relinked nothing leaves
# the binary's timestamp alone and nothing downstream re-runs.
#
# **Between the two of them nothing generated can go stale**, and it is worth saying which covers
# what. An edit to the protocol XML is caught by the generation rule's own DEPENDS below. An edit to
# the *emitter* is caught here: BUILD_ALWAYS recompiles it, the relink moves the executable's
# timestamp, and the rule below depends on the executable. A protocol dropped from the list is caught
# by the generator itself, which deletes anything in its output directory it did not just write.
#
# **Rejected: a CONFIGURE_DEPENDS glob of the generator's sources, named as a dependency as well.** It
# reads like belt and braces and costs a full rebuild of the tree on every single build — the glob
# verification runs each time, re-runs CMake, and a regenerated build.ninja drops the stored header
# dependencies for every translation unit. The mechanism above already covers what the glob was for,
# so the redundancy bought nothing and charged several minutes for it.
set(GYRO_BINDINGS_BINARY_DIR ${CMAKE_BINARY_DIR}/Tools/Bindings)
set(GYRO_BINDINGS_TOOL ${GYRO_BINDINGS_BINARY_DIR}/GyroBindings)


ExternalProject_Add(BindingsGenerator
	SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/Tools/Bindings
	BINARY_DIR ${GYRO_BINDINGS_BINARY_DIR}
	CMAKE_ARGS
		-DCMAKE_BUILD_TYPE=Release
	BUILD_ALWAYS ON
	BUILD_BYPRODUCTS ${GYRO_BINDINGS_TOOL}
	INSTALL_COMMAND ""
	# It builds its own tests, and the main tree runs them — a generator whose parser is not exercised
	# by `ctest --test-dir build` is one whose failures arrive as compiler errors in generated code.
	TEST_COMMAND ""
	USES_TERMINAL_BUILD OFF
)

add_test(
	NAME Bindings
	COMMAND ${GYRO_BINDINGS_BINARY_DIR}/BindingsParserTests
)

# `wl_surface` to `WlSurface`, `xdg-shell` to `XdgShell` — Tools/Bindings/Naming.h's rule, restated
# here because the build has to know an output file's name before the generator has run once.
function(gyro_pascal OUTPUT WIRE)
	string(REPLACE "-" ";" PARTS "${WIRE}")
	string(REPLACE "_" ";" PARTS "${PARTS}")

	set(RESULT "")

	foreach(PART IN LISTS PARTS)
		if(PART STREQUAL "")
			continue()
		endif()

		string(SUBSTRING "${PART}" 0 1 HEAD)
		string(SUBSTRING "${PART}" 1 -1 TAIL)
		string(TOUPPER "${HEAD}" HEAD)
		string(APPEND RESULT "${HEAD}${TAIL}")
	endforeach()

	set(${OUTPUT} "${RESULT}" PARENT_SCOPE)
endfunction()

# One library of generated bindings.
#
#   gyro_add_bindings(WaylandProtocols PROTOCOLS wayland stable/xdg-shell/xdg-shell ...)
#   gyro_add_bindings(WaylandServerProtocols SERVER PROTOCOLS wayland ...)
#
# **`SERVER` is a different library over the same generator**, and everything that differs follows
# from decision 2's split. It writes into `Wayland/Server/` rather than `Wayland/`, so the two trees
# never collide and neither run prunes the other's output. It links `libwayland-server` and *not*
# `Wire` — the server codec is libwayland's, so a server binding reaching for gyro's own codec would
# be the wrong half of the split wired in by accident. And it compiles one extra source with no
# protocol behind it, `Fault.cpp`, which is where the generated code reports gyro's own protocol
# mistakes: libwayland's logger is not an exported symbol, and the other two answers it offers are
# killing the client, which blames the wrong party, and aborting, which takes the machine down.
#
# Each protocol is named by its path *within* one of the two pkgdatadirs and without the `.xml`, which
# is the layout upstream publishes and the spelling somebody adding a protocol can copy off the
# wayland-protocols tree. Both roots are searched, because `wayland.xml` lives in one and everything
# else in the other.
#
# **Every protocol is one invocation of the generator.** Tools/Bindings/Emit.h needs the whole set to
# resolve a reference that leaves its own document — `zwp_linux_buffer_params_v1.created` hands back a
# `wl_buffer` — and a per-file rule would either guess or emit an untyped id where the protocol was
# specific. One rule also means adding a protocol regenerates all of them, rather than leaving the
# file that would have to include it stale until somebody clears the build directory.
function(gyro_add_bindings TARGET)
	cmake_parse_arguments(PARSE_ARGV 1 BINDINGS "SERVER" "" "PROTOCOLS")

	if(BINDINGS_UNPARSED_ARGUMENTS)
		message(FATAL_ERROR "gyro_add_bindings(${TARGET}): unexpected argument ${BINDINGS_UNPARSED_ARGUMENTS}")
	endif()
	if(NOT BINDINGS_PROTOCOLS)
		message(FATAL_ERROR "gyro_add_bindings(${TARGET}): no PROTOCOLS")
	endif()

	set(GENERATED ${CMAKE_BINARY_DIR}/Generated)
	set(INPUTS "")
	set(OUTPUTS "")
	set(SOURCES "")

	if(BINDINGS_SERVER)
		set(SUBDIRECTORY Wayland/Server)
		set(DIRECTION --server)

		# The fault sink and the weak resource, written by the same run. Listed here rather than
		# discovered, because a build rule that globbed its own outputs would be a rule that is right
		# only after the first build. `Weak.h` has no source beside it — it is a template.
		list(APPEND OUTPUTS "${GENERATED}/${SUBDIRECTORY}/Fault.h" "${GENERATED}/${SUBDIRECTORY}/Fault.cpp")
		list(APPEND OUTPUTS "${GENERATED}/${SUBDIRECTORY}/Weak.h")
		list(APPEND SOURCES "${GENERATED}/${SUBDIRECTORY}/Fault.cpp")
	else()
		set(SUBDIRECTORY Wayland)
		set(DIRECTION "")
	endif()

	foreach(PROTOCOL IN LISTS BINDINGS_PROTOCOLS)
		set(FOUND "")

		foreach(ROOT ${GYRO_FIRST_PARTY_PROTOCOLS_DIR} ${GYRO_WAYLAND_DATA_DIR} ${GYRO_WAYLAND_PROTOCOLS_DIR})
			if(EXISTS "${ROOT}/${PROTOCOL}.xml")
				set(FOUND "${ROOT}/${PROTOCOL}.xml")
				break()
			endif()
		endforeach()

		# A protocol the machine does not have is a missing package rather than a typo, most of the
		# time — staging protocols arrive in wayland-protocols releases and a distribution may be a
		# version behind. Both roots are named so the reader can see where it looked.
		if(NOT FOUND)
			message(FATAL_ERROR
				"gyro_add_bindings(${TARGET}): ${PROTOCOL}.xml is in none of "
				"${GYRO_FIRST_PARTY_PROTOCOLS_DIR}, ${GYRO_WAYLAND_DATA_DIR} or "
				"${GYRO_WAYLAND_PROTOCOLS_DIR}. An upstream protocol arrives with wayland-protocols and "
				"a distribution one release behind may not carry it yet; a gyro_ one is a file that "
				"should be in this repository."
			)
		endif()

		get_filename_component(STEM "${PROTOCOL}" NAME_WE)
		gyro_pascal(UNIT "${STEM}")

		list(APPEND INPUTS "${FOUND}")
		list(APPEND OUTPUTS "${GENERATED}/${SUBDIRECTORY}/${UNIT}.h" "${GENERATED}/${SUBDIRECTORY}/${UNIT}.cpp")
		list(APPEND SOURCES "${GENERATED}/${SUBDIRECTORY}/${UNIT}.cpp")
	endforeach()

	# **The rule's output is a stamp and the generated files are byproducts**, which is what makes
	# "never stale" and "never rebuild the world" hold at once. The generator does not rewrite a file
	# whose text is unchanged — that is the whole reason a protocol-suite bump does not recompile
	# everything downstream — and a rule whose declared outputs keep their old timestamps is a rule
	# ninja considers dirty on every build, forever. The stamp is touched unconditionally, so the rule
	# settles; the generated files carry their real timestamps, so each translation unit recompiles
	# only if its own text moved.
	set(STAMP ${CMAKE_CURRENT_BINARY_DIR}/${TARGET}.stamp)

	add_custom_command(
		OUTPUT ${STAMP}
		COMMAND ${GYRO_BINDINGS_TOOL} ${DIRECTION} --output ${GENERATED} ${INPUTS}
		COMMAND ${CMAKE_COMMAND} -E touch ${STAMP}
		BYPRODUCTS ${OUTPUTS}
		# Everything a generated file's text can depend on, so none of them can go stale: the protocol
		# XML it is derived from, and the generator that derived it. The executable rather than the
		# ExternalProject stamp, per the note above — the stamp moves every build and the executable
		# moves only when the generator was actually relinked, which is what an emitter edit does and a
		# no-op build does not. The target is named as well, which is what orders this rule after the
		# sub-build rather than racing it.
		DEPENDS
			${INPUTS}
			${GYRO_BINDINGS_TOOL}
			BindingsGenerator
		COMMENT "Generating Wayland client bindings"
		VERBATIM
	)

	add_custom_target(${TARGET}Generate DEPENDS ${STAMP})

	# A plain library rather than a gyro_add_module, and the difference is where the sources are.
	# CheckPortability and CheckLayering walk Source/ — they police what may run on the frame thread
	# and what a module may name, and neither question is asked of a file the build wrote. What holds
	# this target in place instead is its one edge: it links Wire and nothing else, so a generated
	# binding that reached for a platform header would not link.
	# Written by a rule whose declared output is the stamp, so CMake has to be told they will exist.
	set_source_files_properties(${SOURCES} PROPERTIES GENERATED TRUE)

	add_library(${TARGET} STATIC ${SOURCES})
	add_dependencies(${TARGET} ${TARGET}Generate)
	target_include_directories(${TARGET} PUBLIC ${GENERATED})

	if(BINDINGS_SERVER)
		# `Core` for the descriptor type a request hands over, and libwayland for the codec. Not Wire:
		# decision 2 puts the server codec in libwayland, and a server binding that named gyro's own
		# would be building the half this project decided not to write.
		target_link_libraries(${TARGET} PUBLIC Core PkgConfig::WAYLAND_SERVER)
	else()
		target_link_libraries(${TARGET} PUBLIC Wire)
	endif()
endfunction()
